"""
regime_conditional_test.py -- Test 17

QUESTION: Does RSI(14) mean-reversion work when conditioned on regime?

Context: Test 2 tested RSI UNCONDITIONALLY -> t=0.34, expectancy +0.399%,
rejected as economically worthless. Test 16 (regime classifier) found:
    calm     predictable at 2.25x base rate
    choppy   predictable at 1.29x base rate
    trending predictable at 1.00x  -- ZERO information

HYPOTHESIS: mean-reversion has theoretical reason to work specifically in
choppy (high-vol, directionless) conditions. Test 2 averaged across all
regimes, which would dilute a regime-specific effect toward zero.

HONESTY FLAG: this hypothesis was generated by INSPECTING Test 16's results,
not pre-registered blind. That makes it weaker evidence than a blind test.
The sealed post-2019 window is the only thing that can confirm it.

PRE-REGISTERED PASS CRITERIA (fixed before this script was run):
    1. Choppy-conditioned expectancy per trade > unconditional expectancy
    2. Choppy-conditioned pooled t-statistic > 2.0
    3. Choppy-conditioned beats > 70% of REGIME-MATCHED random traders
    4. Effect exceeds 0.05% round-trip cost
  ALL FOUR required. Anything less = FAIL and the arsenal concept closes.

Evidence boundary: practice window only, through 2018-12-31.
"""

import numpy as np
import pandas as pd
from pathlib import Path

TRAIL        = 60
RSI_PERIOD   = 14
RSI_ENTRY    = 30
RSI_EXIT     = 55
MAX_HOLD     = 20
COST         = 0.0005      # 0.05% round trip (generous vs Alpaca's 0.009%)
PCTL_LO      = 33
PCTL_HI      = 67
N_MONKEY     = 1000
PRACTICE_END = "2018-12-31"
rng = np.random.default_rng(42)

CACHE = Path("data/regime_labels_practice.parquet")

print("=" * 68)
print("TEST 17 -- RSI MEAN-REVERSION CONDITIONED ON REGIME")
print("Practice window only (through 2018-12-31); post-2019 sealed")
print("=" * 68, flush=True)

print("\nLoading price data...", flush=True)
raw = pd.read_parquet("data/yf_universe.parquet",
                      columns=["ticker", "date", "open", "close"])
raw["date"] = pd.to_datetime(raw["date"])
raw = raw[raw["date"] <= PRACTICE_END]
raw = raw[(raw["close"] > 0) & (raw["open"] > 0)]
raw = raw.sort_values(["ticker", "date"]).reset_index(drop=True)
print(f"  {len(raw):,} rows | {raw['ticker'].nunique()} tickers", flush=True)


def wilder_rsi(close: np.ndarray, period: int = RSI_PERIOD) -> np.ndarray:
    """Standard Wilder's RSI."""
    n = len(close)
    out = np.full(n, np.nan)
    if n < period + 1:
        return out
    delta = np.diff(close)
    gain = np.where(delta > 0, delta, 0.0)
    loss = np.where(delta < 0, -delta, 0.0)
    avg_g = gain[:period].mean()
    avg_l = loss[:period].mean()
    for i in range(period, n - 1):
        avg_g = (avg_g * (period - 1) + gain[i]) / period
        avg_l = (avg_l * (period - 1) + loss[i]) / period
        rs = avg_g / avg_l if avg_l > 0 else np.inf
        out[i + 1] = 100.0 - 100.0 / (1.0 + rs)
    return out


print("\nComputing RSI(14) per ticker...", flush=True)
rsi_parts = []
for i, (tk, grp) in enumerate(raw.groupby("ticker", sort=False)):
    if i % 300 == 0:
        print(f"  {i}...", flush=True)
    rsi_parts.append(pd.Series(wilder_rsi(grp["close"].values),
                               index=grp.index))
raw["rsi"] = pd.concat(rsi_parts).sort_index()
print("  done", flush=True)


# ── regime labels (cached: expensive to recompute) ────────────────────────────
def rolling_r2(prices: np.ndarray, window: int = TRAIL) -> np.ndarray:
    x = np.arange(window, dtype=float)
    x -= x.mean()
    ss_xx = (x ** 2).sum()
    out = np.full(len(prices), np.nan)
    with np.errstate(divide="ignore", invalid="ignore"):
        log_p = np.log(prices)
    for i in range(window, len(log_p)):
        y = log_p[i - window:i]
        if not np.isfinite(y).all():
            continue
        y = y - y.mean()
        b = (x * y).sum() / ss_xx
        resid = y - b * x
        ss_tot = (y ** 2).sum()
        out[i] = 1.0 - (resid ** 2).sum() / ss_tot if ss_tot > 0 else 0.0
    return out


def label(vol, r2, vlo, thi):
    if r2 >= thi:
        return "trending"
    elif vol <= vlo:
        return "calm"
    return "choppy"


if CACHE.exists():
    print(f"\nLoading cached regime labels from {CACHE}...", flush=True)
    labels_df = pd.read_parquet(CACHE)
else:
    print("\nComputing regime labels (no cache -- takes ~4 min)...", flush=True)
    raw["log_ret"] = raw.groupby("ticker")["close"].transform(
        lambda s: np.log(s).diff())
    raw["trail_vol"] = (raw.groupby("ticker")["log_ret"].transform(
        lambda s: s.rolling(TRAIL, min_periods=TRAIL).std()) * np.sqrt(252))

    r2_parts = []
    for i, (tk, grp) in enumerate(raw.groupby("ticker", sort=False)):
        if i % 300 == 0:
            print(f"  R2 {i}...", flush=True)
        r2_parts.append(pd.Series(rolling_r2(grp["close"].values),
                                  index=grp.index))
    raw["trend_r2"] = pd.concat(r2_parts).sort_index()

    valid = raw.dropna(subset=["trail_vol", "trend_r2"])
    rows = []
    for d, grp in valid.groupby("date", sort=False):
        if len(grp) < 20:
            continue
        vlo = grp["trail_vol"].quantile(PCTL_LO / 100)
        thi = grp["trend_r2"].quantile(PCTL_HI / 100)
        tmp = grp[["ticker", "date"]].copy()
        tmp["regime"] = [label(v, r, vlo, thi) for v, r
                         in zip(grp["trail_vol"], grp["trend_r2"])]
        rows.append(tmp)
    labels_df = pd.concat(rows, ignore_index=True)
    labels_df.to_parquet(CACHE, index=False)
    print(f"  cached to {CACHE}", flush=True)

print(f"  {len(labels_df):,} labeled stock-days", flush=True)

# ── merge and find entry signals ──────────────────────────────────────────────
print("\nFinding RSI entry signals...", flush=True)
df = raw.merge(labels_df, on=["ticker", "date"], how="inner")
df = df.sort_values(["ticker", "date"]).reset_index(drop=True)

trades = []          # (regime, hold_days, net_return)
for tk, grp in df.groupby("ticker", sort=False):
    rsi   = grp["rsi"].values
    opens = grp["open"].values
    regs  = grp["regime"].values
    n = len(grp)
    i = RSI_PERIOD + 1
    while i < n - 1:
        # entry: RSI crosses UP through 30
        if (np.isfinite(rsi[i - 1]) and np.isfinite(rsi[i])
                and rsi[i - 1] < RSI_ENTRY <= rsi[i]):
            entry_i  = i + 1                      # act next day at OPEN
            entry_px = opens[entry_i]
            entry_reg = regs[i]                   # regime AT SIGNAL (trailing)
            exit_i = None
            for j in range(entry_i, min(entry_i + MAX_HOLD, n - 1)):
                if np.isfinite(rsi[j]) and rsi[j] > RSI_EXIT:
                    exit_i = j + 1
                    break
            if exit_i is None:
                exit_i = min(entry_i + MAX_HOLD, n - 1)
            ret = opens[exit_i] / entry_px - 1.0 - COST
            trades.append((entry_reg, exit_i - entry_i, ret))
            i = exit_i + 1
        else:
            i += 1

tr = pd.DataFrame(trades, columns=["regime", "hold", "ret"])
print(f"  {len(tr):,} trades generated", flush=True)


# ── regime-matched monkey test ────────────────────────────────────────────────
# CRITICAL CONTROL: monkeys must enter on days in the SAME regime, with the
# same holding periods. Otherwise we'd be measuring "choppy days differ"
# rather than "RSI predicts within choppy days."
print("\nBuilding regime-indexed entry pool for monkey test...", flush=True)

pool = {}   # regime -> list of (ticker_open_array, index)
for tk, grp in df.groupby("ticker", sort=False):
    opens = grp["open"].values
    regs  = grp["regime"].values
    for reg in ("calm", "trending", "choppy"):
        idxs = np.where(regs == reg)[0]
        idxs = idxs[(idxs > RSI_PERIOD) & (idxs < len(opens) - MAX_HOLD - 2)]
        if len(idxs):
            pool.setdefault(reg, []).append((opens, idxs))

def monkey_mean(regime, holds, n_sims=N_MONKEY):
    """Mean return of random entries within `regime`, matched holding periods."""
    if regime not in pool or not len(holds):
        return None, None
    entries = pool[regime]
    sims = np.empty(n_sims)
    for s in range(n_sims):
        tot = 0.0
        for h in holds:
            opens, idxs = entries[rng.integers(len(entries))]
            start = int(idxs[rng.integers(len(idxs))])
            end = min(start + h, len(opens) - 1)
            tot += opens[end] / opens[start] - 1.0 - COST
        sims[s] = tot / len(holds)
    return sims.mean(), sims

# ── results ───────────────────────────────────────────────────────────────────
print("\n" + "=" * 68)
print("RESULTS")
print("=" * 68, flush=True)

def stats(sub, name):
    n   = len(sub)
    if n < 30:
        print(f"\n{name}: only {n} trades -- underpowered, skipping")
        return None
    m   = sub["ret"].mean()
    sd  = sub["ret"].std(ddof=1)
    t   = m / (sd / np.sqrt(n))
    win = (sub["ret"] > 0).mean()
    holds = sub["hold"].values
    mk_mean, sims = monkey_mean(name.lower(), holds)
    beat = float((sims < m).mean() * 100) if sims is not None else float("nan")
    print(f"\n{name.upper()}")
    print(f"  trades:            {n:,}")
    print(f"  expectancy/trade:  {m*100:+.3f}%")
    print(f"  win rate:          {win*100:.1f}%")
    print(f"  t-statistic:       {t:.2f}")
    if sims is not None:
        print(f"  regime-matched monkey mean: {mk_mean*100:+.3f}%")
        print(f"  beats {beat:.0f}% of regime-matched monkeys")
    return {"n": n, "exp": m, "t": t, "beat": beat}

uncond_n  = len(tr)
uncond_m  = tr["ret"].mean()
uncond_sd = tr["ret"].std(ddof=1)
uncond_t  = uncond_m / (uncond_sd / np.sqrt(uncond_n))
print(f"\nUNCONDITIONAL (reproduces Test 2)")
print(f"  trades:           {uncond_n:,}")
print(f"  expectancy/trade: {uncond_m*100:+.3f}%")
print(f"  t-statistic:      {uncond_t:.2f}")

res = {}
for reg in ("choppy", "calm", "trending"):
    res[reg] = stats(tr[tr["regime"] == reg], reg)

# ── verdict against pre-registered criteria ───────────────────────────────────
print("\n" + "=" * 68)
print("VERDICT vs PRE-REGISTERED CRITERIA")
print("=" * 68)
c = res.get("choppy")
if c is None:
    print("Choppy bucket underpowered -- FAIL")
else:
    k1 = c["exp"] > uncond_m
    k2 = c["t"] > 2.0
    k3 = c["beat"] > 70.0
    k4 = c["exp"] > COST
    print(f"  1. choppy expectancy > unconditional : "
          f"{'PASS' if k1 else 'FAIL'}  "
          f"({c['exp']*100:+.3f}% vs {uncond_m*100:+.3f}%)")
    print(f"  2. choppy t-stat > 2.0               : "
          f"{'PASS' if k2 else 'FAIL'}  (t={c['t']:.2f})")
    print(f"  3. beats >70% regime-matched monkeys : "
          f"{'PASS' if k3 else 'FAIL'}  ({c['beat']:.0f}%)")
    print(f"  4. exceeds {COST*100:.2f}% cost           : "
          f"{'PASS' if k4 else 'FAIL'}  ({c['exp']*100:+.3f}%)")
    print(f"\n  OVERALL: {'PASS' if all([k1,k2,k3,k4]) else 'FAIL'}")
print("=" * 68, flush=True)
